// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The AnnotationCreateParsed. </summary>
    public partial class AnnotationCreateParsed
    {
        /// <summary> Initializes a new instance of AnnotationCreateParsed. </summary>
        public AnnotationCreateParsed()
        {
        }
    }
}
