// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The AnnotationUpdateParsed. </summary>
    public partial class AnnotationUpdateParsed
    {
        /// <summary> Initializes a new instance of AnnotationUpdateParsed. </summary>
        public AnnotationUpdateParsed()
        {
        }
    }
}
