// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Affinda.API.Models
{
    /// <summary> The BatchAddTagRequest. </summary>
    public partial class BatchAddTagRequest
    {
        /// <summary> Initializes a new instance of BatchAddTagRequest. </summary>
        public BatchAddTagRequest()
        {
            Identifiers = new ChangeTrackingList<string>();
        }

        /// <summary> List of documents to tag. </summary>
        public IList<string> Identifiers { get; }
        /// <summary> The tag&apos;s ID. </summary>
        public int? Tag { get; set; }
    }
}
