// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The Components1Fdmi0OSchemasInvoicedataPropertiesSuppliervatAllof2. </summary>
    public partial class Components1Fdmi0OSchemasInvoicedataPropertiesSuppliervatAllof2
    {
        /// <summary> Initializes a new instance of Components1Fdmi0OSchemasInvoicedataPropertiesSuppliervatAllof2. </summary>
        internal Components1Fdmi0OSchemasInvoicedataPropertiesSuppliervatAllof2()
        {
        }

        /// <summary> Initializes a new instance of Components1Fdmi0OSchemasInvoicedataPropertiesSuppliervatAllof2. </summary>
        /// <param name="raw"></param>
        /// <param name="parsed"></param>
        internal Components1Fdmi0OSchemasInvoicedataPropertiesSuppliervatAllof2(string raw, string parsed)
        {
            Raw = raw;
            Parsed = parsed;
        }

        /// <summary> Gets the raw. </summary>
        public string Raw { get; }
        /// <summary> Gets the parsed. </summary>
        public string Parsed { get; }
    }
}
