// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The ComponentsA69Bd0SchemasInvoicedataPropertiesBpaybillercodeAllof1. </summary>
    public partial class ComponentsA69Bd0SchemasInvoicedataPropertiesBpaybillercodeAllof1
    {
        /// <summary> Initializes a new instance of ComponentsA69Bd0SchemasInvoicedataPropertiesBpaybillercodeAllof1. </summary>
        public ComponentsA69Bd0SchemasInvoicedataPropertiesBpaybillercodeAllof1()
        {
        }

        /// <summary> Initializes a new instance of ComponentsA69Bd0SchemasInvoicedataPropertiesBpaybillercodeAllof1. </summary>
        /// <param name="raw"></param>
        /// <param name="parsed"></param>
        internal ComponentsA69Bd0SchemasInvoicedataPropertiesBpaybillercodeAllof1(string raw, string parsed)
        {
            Raw = raw;
            Parsed = parsed;
        }

        /// <summary> Gets or sets the raw. </summary>
        public string Raw { get; set; }
        /// <summary> Gets or sets the parsed. </summary>
        public string Parsed { get; set; }
    }
}
