// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The Components105Abr3SchemasInvoicedataPropertiesCustomernumberAllof1. </summary>
    public partial class Components105Abr3SchemasInvoicedataPropertiesCustomernumberAllof1
    {
        /// <summary> Initializes a new instance of Components105Abr3SchemasInvoicedataPropertiesCustomernumberAllof1. </summary>
        internal Components105Abr3SchemasInvoicedataPropertiesCustomernumberAllof1()
        {
        }

        /// <summary> Initializes a new instance of Components105Abr3SchemasInvoicedataPropertiesCustomernumberAllof1. </summary>
        /// <param name="raw"></param>
        /// <param name="parsed"></param>
        internal Components105Abr3SchemasInvoicedataPropertiesCustomernumberAllof1(string raw, string parsed)
        {
            Raw = raw;
            Parsed = parsed;
        }

        /// <summary> Gets the raw. </summary>
        public string Raw { get; }
        /// <summary> Gets the parsed. </summary>
        public string Parsed { get; }
    }
}
