// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Affinda.API.Models
{
    /// <summary> The data point to be created for this field. If a data point with the same slug and collection already exists, it will be reused. </summary>
    public partial class DataFieldDataPoint
    {
        /// <summary> Initializes a new instance of DataFieldDataPoint. </summary>
        /// <param name="identifier"> Uniquely identify a data point. </param>
        /// <param name="name"> Name of the data point. </param>
        /// <param name="slug"> A camelCase string that will be used as the key in the API response. </param>
        /// <param name="description"></param>
        /// <param name="type"> The different data types of annotations. </param>
        /// <param name="multiple"></param>
        /// <param name="noRect"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="identifier"/>, <paramref name="name"/> or <paramref name="slug"/> is null. </exception>
        internal DataFieldDataPoint(string identifier, string name, string slug, string description, AnnotationContentType type, bool multiple, bool noRect)
        {
            if (identifier == null)
            {
                throw new ArgumentNullException(nameof(identifier));
            }
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }
            if (slug == null)
            {
                throw new ArgumentNullException(nameof(slug));
            }

            Identifier = identifier;
            Name = name;
            Slug = slug;
            Description = description;
            Type = type;
            Multiple = multiple;
            NoRect = noRect;
        }

        /// <summary> Uniquely identify a data point. </summary>
        public string Identifier { get; }
        /// <summary> Name of the data point. </summary>
        public string Name { get; }
        /// <summary> A camelCase string that will be used as the key in the API response. </summary>
        public string Slug { get; }
        /// <summary> Gets the description. </summary>
        public string Description { get; }
        /// <summary> The different data types of annotations. </summary>
        public AnnotationContentType Type { get; }
        /// <summary> Gets the multiple. </summary>
        public bool Multiple { get; }
        /// <summary> Gets the no rect. </summary>
        public bool NoRect { get; }
    }
}
