// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Affinda.API.Models
{
    /// <summary> The DataPointChoiceForReplace. </summary>
    public partial class DataPointChoiceForReplace
    {
        /// <summary> Initializes a new instance of DataPointChoiceForReplace. </summary>
        /// <param name="value"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public DataPointChoiceForReplace(string value)
        {
            if (value == null)
            {
                throw new ArgumentNullException(nameof(value));
            }

            Value = value;
            Synonyms = new ChangeTrackingList<string>();
        }

        /// <summary> Gets the value. </summary>
        public string Value { get; }
        /// <summary> Gets or sets the label. </summary>
        public string Label { get; set; }
        /// <summary> Gets or sets the synonyms. </summary>
        public IList<string> Synonyms { get; set; }
        /// <summary> Gets or sets the description. </summary>
        public string Description { get; set; }
    }
}
