// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class DataFieldCreateField : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("label");
            writer.WriteStringValue(Label);
            if (Optional.IsDefined(Mandatory))
            {
                writer.WritePropertyName("mandatory");
                writer.WriteBooleanValue(Mandatory.Value);
            }
            if (Optional.IsDefined(ShowDropdown))
            {
                writer.WritePropertyName("showDropdown");
                writer.WriteBooleanValue(ShowDropdown.Value);
            }
            if (Optional.IsDefined(DisplayEnumValue))
            {
                writer.WritePropertyName("displayEnumValue");
                writer.WriteBooleanValue(DisplayEnumValue.Value);
            }
            if (Optional.IsDefined(AutoValidationThreshold))
            {
                if (AutoValidationThreshold != null)
                {
                    writer.WritePropertyName("autoValidationThreshold");
                    writer.WriteNumberValue(AutoValidationThreshold.Value);
                }
                else
                {
                    writer.WriteNull("autoValidationThreshold");
                }
            }
            writer.WriteEndObject();
        }
    }
}
