// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Affinda.API.Models
{
    /// <summary> The Document. </summary>
    public partial class Document
    {
        /// <summary> Initializes a new instance of Document. </summary>
        /// <param name="meta"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="meta"/> is null. </exception>
        internal Document(DocumentMeta meta)
        {
            if (meta == null)
            {
                throw new ArgumentNullException(nameof(meta));
            }

            Meta = meta;
            Data = new ChangeTrackingDictionary<string, object>();
        }

        /// <summary> Initializes a new instance of Document. </summary>
        /// <param name="meta"></param>
        /// <param name="data"> Dictionary of &lt;any&gt;. </param>
        /// <param name="error"></param>
        internal Document(DocumentMeta meta, IReadOnlyDictionary<string, object> data, Error error)
        {
            Meta = meta;
            Data = data;
            Error = error;
        }

        /// <summary> Gets the meta. </summary>
        public DocumentMeta Meta { get; }
        /// <summary> Dictionary of &lt;any&gt;. </summary>
        public IReadOnlyDictionary<string, object> Data { get; }
        /// <summary> Gets the error. </summary>
        public Error Error { get; }
    }
}
