// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> If this document is part of a splitted document, this attribute points to the original document that this document is splitted from. </summary>
    public partial class DocumentMetaParentDocument
    {
        /// <summary> Initializes a new instance of DocumentMetaParentDocument. </summary>
        public DocumentMetaParentDocument()
        {
        }

        /// <summary> Initializes a new instance of DocumentMetaParentDocument. </summary>
        /// <param name="identifier"> Uniquely identify a document. </param>
        internal DocumentMetaParentDocument(string identifier)
        {
            Identifier = identifier;
        }

        /// <summary> Uniquely identify a document. </summary>
        public string Identifier { get; set; }
    }
}
