// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Affinda.API.Models
{
    /// <summary> The Document. </summary>
    public partial class Document
    {
        /// <summary> Initializes a new instance of Document. </summary>
        /// <param name="meta"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="meta"/> is null. </exception>
        public Document(DocumentMeta meta)
        {
            if (meta == null)
            {
                throw new ArgumentNullException(nameof(meta));
            }

            Meta = meta;
            Warnings = new ChangeTrackingList<DocumentWarning>();
        }

        /// <summary> Initializes a new instance of Document. </summary>
        /// <param name="data"> Any object. </param>
        /// <param name="extractor"></param>
        /// <param name="meta"></param>
        /// <param name="error"></param>
        /// <param name="warnings"></param>
        internal Document(object data, string extractor, DocumentMeta meta, DocumentError error, IList<DocumentWarning> warnings)
        {
            Data = data;
            Extractor = extractor;
            Meta = meta;
            Error = error;
            Warnings = warnings;
        }

        /// <summary> Any object. </summary>
        public object Data { get; set; }
        /// <summary> Gets or sets the extractor. </summary>
        internal string Extractor { get; set; }
        /// <summary> Gets or sets the meta. </summary>
        public DocumentMeta Meta { get; set; }
        /// <summary> Gets or sets the error. </summary>
        public DocumentError Error { get; set; }
        /// <summary> Gets the warnings. </summary>
        public IList<DocumentWarning> Warnings { get; }
    }
}
