// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Affinda.API.Models
{
    /// <summary> The EducationDates. </summary>
    public partial class EducationDates
    {
        /// <summary> Initializes a new instance of EducationDates. </summary>
        public EducationDates()
        {
        }

        /// <summary> Initializes a new instance of EducationDates. </summary>
        /// <param name="completionDate"></param>
        /// <param name="isCurrent"></param>
        /// <param name="startDate"></param>
        /// <param name="rawText"></param>
        internal EducationDates(DateTimeOffset? completionDate, bool? isCurrent, DateTimeOffset? startDate, string rawText)
        {
            CompletionDate = completionDate;
            IsCurrent = isCurrent;
            StartDate = startDate;
            RawText = rawText;
        }

        /// <summary> Gets or sets the completion date. </summary>
        public DateTimeOffset? CompletionDate { get; set; }
        /// <summary> Gets or sets the is current. </summary>
        public bool? IsCurrent { get; set; }
        /// <summary> Gets or sets the start date. </summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary> Gets or sets the raw text. </summary>
        public string RawText { get; set; }
    }
}
