// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace Affinda.API.Models
{
    /// <summary> The FieldCategory. </summary>
    public partial class FieldCategory
    {
        /// <summary> Initializes a new instance of FieldCategory. </summary>
        /// <param name="label"></param>
        /// <param name="enabledFields"></param>
        /// <param name="disabledFields"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="label"/>, <paramref name="enabledFields"/> or <paramref name="disabledFields"/> is null. </exception>
        public FieldCategory(string label, IEnumerable<Field> enabledFields, IEnumerable<Field> disabledFields)
        {
            if (label == null)
            {
                throw new ArgumentNullException(nameof(label));
            }
            if (enabledFields == null)
            {
                throw new ArgumentNullException(nameof(enabledFields));
            }
            if (disabledFields == null)
            {
                throw new ArgumentNullException(nameof(disabledFields));
            }

            Label = label;
            EnabledFields = enabledFields.ToList();
            DisabledFields = disabledFields.ToList();
        }

        /// <summary> Initializes a new instance of FieldCategory. </summary>
        /// <param name="label"></param>
        /// <param name="enabledFields"></param>
        /// <param name="disabledFields"></param>
        internal FieldCategory(string label, IList<Field> enabledFields, IList<Field> disabledFields)
        {
            Label = label;
            EnabledFields = enabledFields;
            DisabledFields = disabledFields;
        }

        /// <summary> Gets or sets the label. </summary>
        public string Label { get; set; }
        /// <summary> Gets the enabled fields. </summary>
        public IList<Field> EnabledFields { get; }
        /// <summary> Gets the disabled fields. </summary>
        public IList<Field> DisabledFields { get; }
    }
}
