// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Affinda.API.Models
{
    /// <summary> The InvoiceMeta. </summary>
    public partial class InvoiceMeta : Meta
    {
        /// <summary> Initializes a new instance of InvoiceMeta. </summary>
        /// <param name="identifier"> Unique identifier for the document. If creating a document and left blank, one will be automatically generated. </param>
        /// <param name="ready"> If true, the document has finished processing. Particularly useful if an endpoint request specified wait=False, when polling use this variable to determine when to stop polling. </param>
        /// <param name="failed"> If true, some exception was raised during processing. Check the &apos;error&apos; field of the main return object. </param>
        internal InvoiceMeta(string identifier, bool ready, bool failed) : base(identifier, ready, failed)
        {
        }

        /// <summary> Initializes a new instance of InvoiceMeta. </summary>
        /// <param name="identifier"> Unique identifier for the document. If creating a document and left blank, one will be automatically generated. </param>
        /// <param name="fileName"> Optional filename of the file. </param>
        /// <param name="ready"> If true, the document has finished processing. Particularly useful if an endpoint request specified wait=False, when polling use this variable to determine when to stop polling. </param>
        /// <param name="readyDt"> The datetime when the document was ready. </param>
        /// <param name="failed"> If true, some exception was raised during processing. Check the &apos;error&apos; field of the main return object. </param>
        /// <param name="expiryTime"> The date/time in ISO-8601 format when the document will be automatically deleted.  Defaults to no expiry. </param>
        /// <param name="reviewUrl"> Signed URL (valid for 60 minutes) to access the invoice review tool. </param>
        internal InvoiceMeta(string identifier, string fileName, bool ready, DateTimeOffset? readyDt, bool failed, string expiryTime, string reviewUrl) : base(identifier, fileName, ready, readyDt, failed, expiryTime)
        {
            ReviewUrl = reviewUrl;
        }

        /// <summary> Signed URL (valid for 60 minutes) to access the invoice review tool. </summary>
        public string ReviewUrl { get; }
    }
}
