// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class InvoiceData
    {
        internal static InvoiceData DeserializeInvoiceData(JsonElement element)
        {
            Optional<string> invoiceDate = default;
            Optional<string> invoiceOrderDate = default;
            Optional<string> paymentDateDue = default;
            Optional<string> paymentAmountBase = default;
            Optional<string> paymentAmountTax = default;
            Optional<string> paymentAmountTotal = default;
            Optional<string> paymentAmountPaid = default;
            Optional<string> paymentAmountDue = default;
            Optional<string> invoiceNumber = default;
            Optional<string> invoicePurchaseOrderNumber = default;
            Optional<string> supplierBusinessNumber = default;
            Optional<string> customerNumber = default;
            Optional<string> customerBusinessNumber = default;
            Optional<string> paymentReference = default;
            Optional<string> bankAccountNumber = default;
            Optional<string> supplierVAT = default;
            Optional<string> customerVAT = default;
            Optional<string> bpayBillerCode = default;
            Optional<string> bpayReference = default;
            Optional<string> bankSortCode = default;
            Optional<string> bankIBAN = default;
            Optional<string> bankSwift = default;
            Optional<string> bankBSB = default;
            Optional<string> customerContactName = default;
            Optional<string> customerCompanyName = default;
            Optional<string> supplierCompanyName = default;
            Optional<Location> customerBillingAddress = default;
            Optional<Location> customerDeliveryAddress = default;
            Optional<Location> supplierAddress = default;
            Optional<string> customerPhoneNumber = default;
            Optional<string> supplierPhoneNumber = default;
            Optional<string> supplierFax = default;
            Optional<string> customerEmail = default;
            Optional<string> supplierEmail = default;
            Optional<string> supplierWebsite = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("invoiceDate"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        invoiceDate = null;
                        continue;
                    }
                    invoiceDate = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("invoiceOrderDate"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        invoiceOrderDate = null;
                        continue;
                    }
                    invoiceOrderDate = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("paymentDateDue"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        paymentDateDue = null;
                        continue;
                    }
                    paymentDateDue = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("paymentAmountBase"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        paymentAmountBase = null;
                        continue;
                    }
                    paymentAmountBase = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("paymentAmountTax"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        paymentAmountTax = null;
                        continue;
                    }
                    paymentAmountTax = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("paymentAmountTotal"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        paymentAmountTotal = null;
                        continue;
                    }
                    paymentAmountTotal = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("paymentAmountPaid"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        paymentAmountPaid = null;
                        continue;
                    }
                    paymentAmountPaid = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("paymentAmountDue"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        paymentAmountDue = null;
                        continue;
                    }
                    paymentAmountDue = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("invoiceNumber"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        invoiceNumber = null;
                        continue;
                    }
                    invoiceNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("invoicePurchaseOrderNumber"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        invoicePurchaseOrderNumber = null;
                        continue;
                    }
                    invoicePurchaseOrderNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("supplierBusinessNumber"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        supplierBusinessNumber = null;
                        continue;
                    }
                    supplierBusinessNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("customerNumber"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        customerNumber = null;
                        continue;
                    }
                    customerNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("customerBusinessNumber"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        customerBusinessNumber = null;
                        continue;
                    }
                    customerBusinessNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("paymentReference"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        paymentReference = null;
                        continue;
                    }
                    paymentReference = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bankAccountNumber"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        bankAccountNumber = null;
                        continue;
                    }
                    bankAccountNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("supplierVAT"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        supplierVAT = null;
                        continue;
                    }
                    supplierVAT = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("customerVAT"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        customerVAT = null;
                        continue;
                    }
                    customerVAT = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bpayBillerCode"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        bpayBillerCode = null;
                        continue;
                    }
                    bpayBillerCode = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bpayReference"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        bpayReference = null;
                        continue;
                    }
                    bpayReference = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bankSortCode"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        bankSortCode = null;
                        continue;
                    }
                    bankSortCode = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bankIBAN"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        bankIBAN = null;
                        continue;
                    }
                    bankIBAN = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bankSwift"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        bankSwift = null;
                        continue;
                    }
                    bankSwift = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bankBSB"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        bankBSB = null;
                        continue;
                    }
                    bankBSB = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("customerContactName"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        customerContactName = null;
                        continue;
                    }
                    customerContactName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("customerCompanyName"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        customerCompanyName = null;
                        continue;
                    }
                    customerCompanyName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("supplierCompanyName"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        supplierCompanyName = null;
                        continue;
                    }
                    supplierCompanyName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("customerBillingAddress"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        customerBillingAddress = null;
                        continue;
                    }
                    customerBillingAddress = Location.DeserializeLocation(property.Value);
                    continue;
                }
                if (property.NameEquals("customerDeliveryAddress"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        customerDeliveryAddress = null;
                        continue;
                    }
                    customerDeliveryAddress = Location.DeserializeLocation(property.Value);
                    continue;
                }
                if (property.NameEquals("supplierAddress"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        supplierAddress = null;
                        continue;
                    }
                    supplierAddress = Location.DeserializeLocation(property.Value);
                    continue;
                }
                if (property.NameEquals("customerPhoneNumber"))
                {
                    customerPhoneNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("supplierPhoneNumber"))
                {
                    supplierPhoneNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("supplierFax"))
                {
                    supplierFax = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("customerEmail"))
                {
                    customerEmail = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("supplierEmail"))
                {
                    supplierEmail = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("supplierWebsite"))
                {
                    supplierWebsite = property.Value.GetString();
                    continue;
                }
            }
            return new InvoiceData(invoiceDate.Value, invoiceOrderDate.Value, paymentDateDue.Value, paymentAmountBase.Value, paymentAmountTax.Value, paymentAmountTotal.Value, paymentAmountPaid.Value, paymentAmountDue.Value, invoiceNumber.Value, invoicePurchaseOrderNumber.Value, supplierBusinessNumber.Value, customerNumber.Value, customerBusinessNumber.Value, paymentReference.Value, bankAccountNumber.Value, supplierVAT.Value, customerVAT.Value, bpayBillerCode.Value, bpayReference.Value, bankSortCode.Value, bankIBAN.Value, bankSwift.Value, bankBSB.Value, customerContactName.Value, customerCompanyName.Value, supplierCompanyName.Value, customerBillingAddress.Value, customerDeliveryAddress.Value, supplierAddress.Value, customerPhoneNumber.Value, supplierPhoneNumber.Value, supplierFax.Value, customerEmail.Value, supplierEmail.Value, supplierWebsite.Value);
        }
    }
}
