// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Affinda.API.Models
{
    /// <summary> The InvoiceData. </summary>
    public partial class InvoiceData
    {
        /// <summary> Initializes a new instance of InvoiceData. </summary>
        public InvoiceData()
        {
            Tables = new ChangeTrackingList<InvoiceDataTablesItem>();
            CustomFields = new ChangeTrackingDictionary<string, object>();
        }

        /// <summary> Initializes a new instance of InvoiceData. </summary>
        /// <param name="tables"></param>
        /// <param name="invoiceDate"></param>
        /// <param name="invoiceOrderDate"></param>
        /// <param name="paymentDateDue"></param>
        /// <param name="paymentAmountBase"></param>
        /// <param name="paymentAmountTax"></param>
        /// <param name="paymentAmountTotal"></param>
        /// <param name="paymentAmountPaid"></param>
        /// <param name="paymentAmountDue"></param>
        /// <param name="invoiceNumber"></param>
        /// <param name="invoicePurchaseOrderNumber"></param>
        /// <param name="supplierBusinessNumber"></param>
        /// <param name="customerNumber"></param>
        /// <param name="customerBusinessNumber"></param>
        /// <param name="paymentReference"></param>
        /// <param name="bankAccountNumber"></param>
        /// <param name="supplierVat"></param>
        /// <param name="customerVat"></param>
        /// <param name="bpayBillerCode"></param>
        /// <param name="bpayReference"></param>
        /// <param name="bankSortCode"></param>
        /// <param name="bankIban"></param>
        /// <param name="bankSwift"></param>
        /// <param name="bankBsb"></param>
        /// <param name="customerContactName"></param>
        /// <param name="customerCompanyName"></param>
        /// <param name="supplierCompanyName"></param>
        /// <param name="customerBillingAddress"></param>
        /// <param name="customerDeliveryAddress"></param>
        /// <param name="supplierAddress"></param>
        /// <param name="customerPhoneNumber"></param>
        /// <param name="supplierPhoneNumber"></param>
        /// <param name="supplierFax"></param>
        /// <param name="customerEmail"></param>
        /// <param name="supplierEmail"></param>
        /// <param name="supplierWebsite"></param>
        /// <param name="currencyCode"></param>
        /// <param name="customFields"> Dictionary of &lt;any&gt;. </param>
        internal InvoiceData(IList<InvoiceDataTablesItem> tables, DateAnnotation invoiceDate, DateAnnotation invoiceOrderDate, DateAnnotation paymentDateDue, InvoiceDataPaymentAmountBase paymentAmountBase, InvoiceDataPaymentAmountTax paymentAmountTax, InvoiceDataPaymentAmountTotal paymentAmountTotal, InvoiceDataPaymentAmountPaid paymentAmountPaid, InvoiceDataPaymentAmountDue paymentAmountDue, InvoiceDataInvoiceNumber invoiceNumber, InvoiceDataInvoicePurchaseOrderNumber invoicePurchaseOrderNumber, InvoiceDataSupplierBusinessNumber supplierBusinessNumber, InvoiceDataCustomerNumber customerNumber, InvoiceDataCustomerBusinessNumber customerBusinessNumber, InvoiceDataPaymentReference paymentReference, InvoiceDataBankAccountNumber bankAccountNumber, InvoiceDataSupplierVat supplierVat, InvoiceDataCustomerVat customerVat, InvoiceDataBpayBillerCode bpayBillerCode, InvoiceDataBpayReference bpayReference, InvoiceDataBankSortCode bankSortCode, InvoiceDataBankIban bankIban, InvoiceDataBankSwift bankSwift, InvoiceDataBankBsb bankBsb, InvoiceDataCustomerContactName customerContactName, InvoiceDataCustomerCompanyName customerCompanyName, InvoiceDataSupplierCompanyName supplierCompanyName, LocationAnnotation customerBillingAddress, LocationAnnotation customerDeliveryAddress, LocationAnnotation supplierAddress, InvoiceDataCustomerPhoneNumber customerPhoneNumber, InvoiceDataSupplierPhoneNumber supplierPhoneNumber, InvoiceDataSupplierFax supplierFax, InvoiceDataCustomerEmail customerEmail, InvoiceDataSupplierEmail supplierEmail, InvoiceDataSupplierWebsite supplierWebsite, TextAnnotation currencyCode, IDictionary<string, object> customFields)
        {
            Tables = tables;
            InvoiceDate = invoiceDate;
            InvoiceOrderDate = invoiceOrderDate;
            PaymentDateDue = paymentDateDue;
            PaymentAmountBase = paymentAmountBase;
            PaymentAmountTax = paymentAmountTax;
            PaymentAmountTotal = paymentAmountTotal;
            PaymentAmountPaid = paymentAmountPaid;
            PaymentAmountDue = paymentAmountDue;
            InvoiceNumber = invoiceNumber;
            InvoicePurchaseOrderNumber = invoicePurchaseOrderNumber;
            SupplierBusinessNumber = supplierBusinessNumber;
            CustomerNumber = customerNumber;
            CustomerBusinessNumber = customerBusinessNumber;
            PaymentReference = paymentReference;
            BankAccountNumber = bankAccountNumber;
            SupplierVat = supplierVat;
            CustomerVat = customerVat;
            BpayBillerCode = bpayBillerCode;
            BpayReference = bpayReference;
            BankSortCode = bankSortCode;
            BankIban = bankIban;
            BankSwift = bankSwift;
            BankBsb = bankBsb;
            CustomerContactName = customerContactName;
            CustomerCompanyName = customerCompanyName;
            SupplierCompanyName = supplierCompanyName;
            CustomerBillingAddress = customerBillingAddress;
            CustomerDeliveryAddress = customerDeliveryAddress;
            SupplierAddress = supplierAddress;
            CustomerPhoneNumber = customerPhoneNumber;
            SupplierPhoneNumber = supplierPhoneNumber;
            SupplierFax = supplierFax;
            CustomerEmail = customerEmail;
            SupplierEmail = supplierEmail;
            SupplierWebsite = supplierWebsite;
            CurrencyCode = currencyCode;
            CustomFields = customFields;
        }

        /// <summary> Gets the tables. </summary>
        public IList<InvoiceDataTablesItem> Tables { get; }
        /// <summary> Gets or sets the invoice date. </summary>
        public DateAnnotation InvoiceDate { get; set; }
        /// <summary> Gets or sets the invoice order date. </summary>
        public DateAnnotation InvoiceOrderDate { get; set; }
        /// <summary> Gets or sets the payment date due. </summary>
        public DateAnnotation PaymentDateDue { get; set; }
        /// <summary> Gets or sets the payment amount base. </summary>
        public InvoiceDataPaymentAmountBase PaymentAmountBase { get; set; }
        /// <summary> Gets or sets the payment amount tax. </summary>
        public InvoiceDataPaymentAmountTax PaymentAmountTax { get; set; }
        /// <summary> Gets or sets the payment amount total. </summary>
        public InvoiceDataPaymentAmountTotal PaymentAmountTotal { get; set; }
        /// <summary> Gets or sets the payment amount paid. </summary>
        public InvoiceDataPaymentAmountPaid PaymentAmountPaid { get; set; }
        /// <summary> Gets or sets the payment amount due. </summary>
        public InvoiceDataPaymentAmountDue PaymentAmountDue { get; set; }
        /// <summary> Gets or sets the invoice number. </summary>
        public InvoiceDataInvoiceNumber InvoiceNumber { get; set; }
        /// <summary> Gets or sets the invoice purchase order number. </summary>
        public InvoiceDataInvoicePurchaseOrderNumber InvoicePurchaseOrderNumber { get; set; }
        /// <summary> Gets or sets the supplier business number. </summary>
        public InvoiceDataSupplierBusinessNumber SupplierBusinessNumber { get; set; }
        /// <summary> Gets or sets the customer number. </summary>
        public InvoiceDataCustomerNumber CustomerNumber { get; set; }
        /// <summary> Gets or sets the customer business number. </summary>
        public InvoiceDataCustomerBusinessNumber CustomerBusinessNumber { get; set; }
        /// <summary> Gets or sets the payment reference. </summary>
        public InvoiceDataPaymentReference PaymentReference { get; set; }
        /// <summary> Gets or sets the bank account number. </summary>
        public InvoiceDataBankAccountNumber BankAccountNumber { get; set; }
        /// <summary> Gets or sets the supplier vat. </summary>
        public InvoiceDataSupplierVat SupplierVat { get; set; }
        /// <summary> Gets or sets the customer vat. </summary>
        public InvoiceDataCustomerVat CustomerVat { get; set; }
        /// <summary> Gets or sets the bpay biller code. </summary>
        public InvoiceDataBpayBillerCode BpayBillerCode { get; set; }
        /// <summary> Gets or sets the bpay reference. </summary>
        public InvoiceDataBpayReference BpayReference { get; set; }
        /// <summary> Gets or sets the bank sort code. </summary>
        public InvoiceDataBankSortCode BankSortCode { get; set; }
        /// <summary> Gets or sets the bank iban. </summary>
        public InvoiceDataBankIban BankIban { get; set; }
        /// <summary> Gets or sets the bank swift. </summary>
        public InvoiceDataBankSwift BankSwift { get; set; }
        /// <summary> Gets or sets the bank bsb. </summary>
        public InvoiceDataBankBsb BankBsb { get; set; }
        /// <summary> Gets or sets the customer contact name. </summary>
        public InvoiceDataCustomerContactName CustomerContactName { get; set; }
        /// <summary> Gets or sets the customer company name. </summary>
        public InvoiceDataCustomerCompanyName CustomerCompanyName { get; set; }
        /// <summary> Gets or sets the supplier company name. </summary>
        public InvoiceDataSupplierCompanyName SupplierCompanyName { get; set; }
        /// <summary> Gets or sets the customer billing address. </summary>
        public LocationAnnotation CustomerBillingAddress { get; set; }
        /// <summary> Gets or sets the customer delivery address. </summary>
        public LocationAnnotation CustomerDeliveryAddress { get; set; }
        /// <summary> Gets or sets the supplier address. </summary>
        public LocationAnnotation SupplierAddress { get; set; }
        /// <summary> Gets or sets the customer phone number. </summary>
        public InvoiceDataCustomerPhoneNumber CustomerPhoneNumber { get; set; }
        /// <summary> Gets or sets the supplier phone number. </summary>
        public InvoiceDataSupplierPhoneNumber SupplierPhoneNumber { get; set; }
        /// <summary> Gets or sets the supplier fax. </summary>
        public InvoiceDataSupplierFax SupplierFax { get; set; }
        /// <summary> Gets or sets the customer email. </summary>
        public InvoiceDataCustomerEmail CustomerEmail { get; set; }
        /// <summary> Gets or sets the supplier email. </summary>
        public InvoiceDataSupplierEmail SupplierEmail { get; set; }
        /// <summary> Gets or sets the supplier website. </summary>
        public InvoiceDataSupplierWebsite SupplierWebsite { get; set; }
        /// <summary> Gets or sets the currency code. </summary>
        public TextAnnotation CurrencyCode { get; set; }
        /// <summary> Dictionary of &lt;any&gt;. </summary>
        public IDictionary<string, object> CustomFields { get; set; }
    }
}
