// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> Customize the theme of the embeded search tool. </summary>
    public partial class JobDescriptionSearchConfigSearchToolTheme : ThemeConfig
    {
        /// <summary> Initializes a new instance of JobDescriptionSearchConfigSearchToolTheme. </summary>
        public JobDescriptionSearchConfigSearchToolTheme()
        {
        }

        /// <summary> Initializes a new instance of JobDescriptionSearchConfigSearchToolTheme. </summary>
        /// <param name="palette"></param>
        /// <param name="typography"></param>
        /// <param name="borderRadius"></param>
        /// <param name="fontUrl"></param>
        internal JobDescriptionSearchConfigSearchToolTheme(ThemeConfigPalette palette, ThemeConfigTypography typography, float? borderRadius, string fontUrl) : base(palette, typography, borderRadius, fontUrl)
        {
        }
    }
}
