// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Affinda.API.Models
{
    /// <summary> The JobDescriptionSearchDetailOccupationGroupValueItem. </summary>
    public partial class JobDescriptionSearchDetailOccupationGroupValueItem : OccupationGroup
    {
        /// <summary> Initializes a new instance of JobDescriptionSearchDetailOccupationGroupValueItem. </summary>
        /// <param name="code"></param>
        /// <param name="name"></param>
        /// <param name="children"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="name"/> or <paramref name="children"/> is null. </exception>
        internal JobDescriptionSearchDetailOccupationGroupValueItem(int code, string name, IEnumerable<OccupationGroup> children) : base(code, name, children)
        {
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }
            if (children == null)
            {
                throw new ArgumentNullException(nameof(children));
            }
        }

        /// <summary> Initializes a new instance of JobDescriptionSearchDetailOccupationGroupValueItem. </summary>
        /// <param name="code"></param>
        /// <param name="name"></param>
        /// <param name="children"></param>
        /// <param name="match"></param>
        internal JobDescriptionSearchDetailOccupationGroupValueItem(int code, string name, IReadOnlyList<OccupationGroup> children, bool? match) : base(code, name, children)
        {
            Match = match;
        }

        /// <summary> Gets the match. </summary>
        public bool? Match { get; }
    }
}
