// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Affinda.API.Models
{
    /// <summary> The JobDescriptionSearchResult. </summary>
    public partial class JobDescriptionSearchResult
    {
        /// <summary> Initializes a new instance of JobDescriptionSearchResult. </summary>
        /// <param name="identifier"> A random string that uniquely identify the resource. </param>
        /// <param name="score"></param>
        /// <param name="pdf"></param>
        /// <param name="jobTitle"></param>
        /// <param name="managementLevel"></param>
        /// <param name="experience"></param>
        /// <param name="skills"></param>
        /// <param name="languages"></param>
        /// <param name="location"></param>
        /// <param name="education"></param>
        /// <param name="searchExpression"></param>
        /// <param name="organizationName"></param>
        /// <param name="customData"> Dictionary of &lt;components·nqbw24·schemas·customdatasearchscorecomponent·additionalproperties&gt;. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="identifier"/>, <paramref name="pdf"/>, <paramref name="jobTitle"/>, <paramref name="managementLevel"/>, <paramref name="experience"/>, <paramref name="skills"/>, <paramref name="languages"/>, <paramref name="location"/>, <paramref name="education"/>, <paramref name="searchExpression"/> or <paramref name="customData"/> is null. </exception>
        internal JobDescriptionSearchResult(string identifier, float score, string pdf, JobTitleSearchScoreComponent jobTitle, ManagementLevelSearchScoreComponent managementLevel, ExperienceSearchScoreComponent experience, SkillsSearchScoreComponent skills, LanguagesSearchScoreComponent languages, LocationSearchScoreComponent location, EducationSearchScoreComponent education, SearchExpressionSearchScoreComponent searchExpression, string organizationName, IReadOnlyDictionary<string, ComponentsNqbw24SchemasCustomdatasearchscorecomponentAdditionalproperties> customData)
        {
            if (identifier == null)
            {
                throw new ArgumentNullException(nameof(identifier));
            }
            if (pdf == null)
            {
                throw new ArgumentNullException(nameof(pdf));
            }
            if (jobTitle == null)
            {
                throw new ArgumentNullException(nameof(jobTitle));
            }
            if (managementLevel == null)
            {
                throw new ArgumentNullException(nameof(managementLevel));
            }
            if (experience == null)
            {
                throw new ArgumentNullException(nameof(experience));
            }
            if (skills == null)
            {
                throw new ArgumentNullException(nameof(skills));
            }
            if (languages == null)
            {
                throw new ArgumentNullException(nameof(languages));
            }
            if (location == null)
            {
                throw new ArgumentNullException(nameof(location));
            }
            if (education == null)
            {
                throw new ArgumentNullException(nameof(education));
            }
            if (searchExpression == null)
            {
                throw new ArgumentNullException(nameof(searchExpression));
            }
            if (customData == null)
            {
                throw new ArgumentNullException(nameof(customData));
            }

            Identifier = identifier;
            Score = score;
            Pdf = pdf;
            JobTitle = jobTitle;
            ManagementLevel = managementLevel;
            Experience = experience;
            Skills = skills;
            Languages = languages;
            Location = location;
            Education = education;
            SearchExpression = searchExpression;
            OrganizationName = organizationName;
            CustomData = customData;
        }

        /// <summary> Initializes a new instance of JobDescriptionSearchResult. </summary>
        /// <param name="identifier"> A random string that uniquely identify the resource. </param>
        /// <param name="score"></param>
        /// <param name="pdf"></param>
        /// <param name="jobTitle"></param>
        /// <param name="managementLevel"></param>
        /// <param name="experience"></param>
        /// <param name="skills"></param>
        /// <param name="languages"></param>
        /// <param name="location"></param>
        /// <param name="education"></param>
        /// <param name="occupationGroup"></param>
        /// <param name="searchExpression"></param>
        /// <param name="organizationName"></param>
        /// <param name="customData"> Dictionary of &lt;components·nqbw24·schemas·customdatasearchscorecomponent·additionalproperties&gt;. </param>
        internal JobDescriptionSearchResult(string identifier, float score, string pdf, JobTitleSearchScoreComponent jobTitle, ManagementLevelSearchScoreComponent managementLevel, ExperienceSearchScoreComponent experience, SkillsSearchScoreComponent skills, LanguagesSearchScoreComponent languages, LocationSearchScoreComponent location, EducationSearchScoreComponent education, OccupationGroupSearchScoreComponent occupationGroup, SearchExpressionSearchScoreComponent searchExpression, string organizationName, IReadOnlyDictionary<string, ComponentsNqbw24SchemasCustomdatasearchscorecomponentAdditionalproperties> customData)
        {
            Identifier = identifier;
            Score = score;
            Pdf = pdf;
            JobTitle = jobTitle;
            ManagementLevel = managementLevel;
            Experience = experience;
            Skills = skills;
            Languages = languages;
            Location = location;
            Education = education;
            OccupationGroup = occupationGroup;
            SearchExpression = searchExpression;
            OrganizationName = organizationName;
            CustomData = customData;
        }

        /// <summary> A random string that uniquely identify the resource. </summary>
        public string Identifier { get; }
        /// <summary> Gets the score. </summary>
        public float Score { get; }
        /// <summary> Gets the pdf. </summary>
        public string Pdf { get; }
        /// <summary> Gets the job title. </summary>
        public JobTitleSearchScoreComponent JobTitle { get; }
        /// <summary> Gets the management level. </summary>
        public ManagementLevelSearchScoreComponent ManagementLevel { get; }
        /// <summary> Gets the experience. </summary>
        public ExperienceSearchScoreComponent Experience { get; }
        /// <summary> Gets the skills. </summary>
        public SkillsSearchScoreComponent Skills { get; }
        /// <summary> Gets the languages. </summary>
        public LanguagesSearchScoreComponent Languages { get; }
        /// <summary> Gets the location. </summary>
        public LocationSearchScoreComponent Location { get; }
        /// <summary> Gets the education. </summary>
        public EducationSearchScoreComponent Education { get; }
        /// <summary> Gets the occupation group. </summary>
        public OccupationGroupSearchScoreComponent OccupationGroup { get; }
        /// <summary> Gets the search expression. </summary>
        public SearchExpressionSearchScoreComponent SearchExpression { get; }
        /// <summary> Gets the organization name. </summary>
        public string OrganizationName { get; }
        /// <summary> Dictionary of &lt;components·nqbw24·schemas·customdatasearchscorecomponent·additionalproperties&gt;. </summary>
        public IReadOnlyDictionary<string, ComponentsNqbw24SchemasCustomdatasearchscorecomponentAdditionalproperties> CustomData { get; }
    }
}
