// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Affinda.API.Models
{
    /// <summary> The JobDescriptionSearch. </summary>
    public partial class JobDescriptionSearch
    {
        /// <summary> Initializes a new instance of JobDescriptionSearch. </summary>
        internal JobDescriptionSearch()
        {
            Results = new ChangeTrackingList<JobDescriptionSearchResult>();
        }

        /// <summary> Initializes a new instance of JobDescriptionSearch. </summary>
        /// <param name="count"> Total number of results. </param>
        /// <param name="next"> URL to request next page of results. </param>
        /// <param name="previous"> URL to request previous page of results. </param>
        /// <param name="parameters"></param>
        /// <param name="results"></param>
        internal JobDescriptionSearch(int? count, string next, string previous, JobDescriptionSearchParameters parameters, IReadOnlyList<JobDescriptionSearchResult> results)
        {
            Count = count;
            Next = next;
            Previous = previous;
            Parameters = parameters;
            Results = results;
        }

        /// <summary> Total number of results. </summary>
        public int? Count { get; }
        /// <summary> URL to request next page of results. </summary>
        public string Next { get; }
        /// <summary> URL to request previous page of results. </summary>
        public string Previous { get; }
        /// <summary> Gets the parameters. </summary>
        public JobDescriptionSearchParameters Parameters { get; }
        /// <summary> Gets the results. </summary>
        public IReadOnlyList<JobDescriptionSearchResult> Results { get; }
    }
}
