// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The JobDescriptionSearchDetailManagementLevel. </summary>
    public partial class JobDescriptionSearchDetailManagementLevel
    {
        /// <summary> Initializes a new instance of JobDescriptionSearchDetailManagementLevel. </summary>
        internal JobDescriptionSearchDetailManagementLevel()
        {
        }

        /// <summary> Initializes a new instance of JobDescriptionSearchDetailManagementLevel. </summary>
        /// <param name="level"></param>
        /// <param name="match"></param>
        internal JobDescriptionSearchDetailManagementLevel(ManagementLevel? level, bool? match)
        {
            Level = level;
            Match = match;
        }

        /// <summary> Gets the level. </summary>
        public ManagementLevel? Level { get; }
        /// <summary> Gets the match. </summary>
        public bool? Match { get; }
    }
}
