// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class Mapping
    {
        internal static Mapping DeserializeMapping(JsonElement element)
        {
            string identifier = default;
            Optional<string> organization = default;
            string dataSource = default;
            Optional<float?> scoreCutoff = default;
            Optional<string> orderBy = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("identifier"))
                {
                    identifier = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("organization"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        organization = null;
                        continue;
                    }
                    organization = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("dataSource"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        dataSource = null;
                        continue;
                    }
                    dataSource = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("scoreCutoff"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        scoreCutoff = null;
                        continue;
                    }
                    scoreCutoff = property.Value.GetSingle();
                    continue;
                }
                if (property.NameEquals("orderBy"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        orderBy = null;
                        continue;
                    }
                    orderBy = property.Value.GetString();
                    continue;
                }
            }
            return new Mapping(identifier, organization.Value, dataSource, Optional.ToNullable(scoreCutoff), orderBy.Value);
        }
    }
}
