// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class Organization
    {
        internal static Organization DeserializeOrganization(JsonElement element)
        {
            Optional<string> identifier = default;
            Optional<string> name = default;
            Optional<OrganizationUserRole?> userRole = default;
            Optional<string> avatar = default;
            Optional<string> resthookSignatureKey = default;
            Optional<bool> isTrial = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("identifier"))
                {
                    identifier = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("userRole"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        userRole = null;
                        continue;
                    }
                    userRole = new OrganizationUserRole(property.Value.GetString());
                    continue;
                }
                if (property.NameEquals("avatar"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        avatar = null;
                        continue;
                    }
                    avatar = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("resthookSignatureKey"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        resthookSignatureKey = null;
                        continue;
                    }
                    resthookSignatureKey = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("isTrial"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    isTrial = property.Value.GetBoolean();
                    continue;
                }
            }
            return new Organization(identifier.Value, name.Value, Optional.ToNullable(userRole), avatar.Value, resthookSignatureKey.Value, Optional.ToNullable(isTrial));
        }
    }
}
