// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The Paths1Mc0Je6IndexPostResponses201ContentApplicationJsonSchema. </summary>
    public partial class Paths1Mc0Je6IndexPostResponses201ContentApplicationJsonSchema
    {
        /// <summary> Initializes a new instance of Paths1Mc0Je6IndexPostResponses201ContentApplicationJsonSchema. </summary>
        internal Paths1Mc0Je6IndexPostResponses201ContentApplicationJsonSchema()
        {
        }

        /// <summary> Initializes a new instance of Paths1Mc0Je6IndexPostResponses201ContentApplicationJsonSchema. </summary>
        /// <param name="name"></param>
        /// <param name="documentType"></param>
        internal Paths1Mc0Je6IndexPostResponses201ContentApplicationJsonSchema(string name, Enum4? documentType)
        {
            Name = name;
            DocumentType = documentType;
        }

        /// <summary> Gets the name. </summary>
        public string Name { get; }
        /// <summary> Gets the document type. </summary>
        public Enum4? DocumentType { get; }
    }
}
