// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class Paths108CfgmIndexGetResponses200ContentApplicationJsonSchemaPropertiesResultsItems
    {
        internal static Paths108CfgmIndexGetResponses200ContentApplicationJsonSchemaPropertiesResultsItems DeserializePaths108CfgmIndexGetResponses200ContentApplicationJsonSchemaPropertiesResultsItems(JsonElement element)
        {
            string name = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
            }
            return new Paths108CfgmIndexGetResponses200ContentApplicationJsonSchemaPropertiesResultsItems(name);
        }
    }
}
