// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The Paths2T1Oc0ResumeSearchEmbedPostRequestbodyContentApplicationJsonSchema. </summary>
    public partial class Paths2T1Oc0ResumeSearchEmbedPostRequestbodyContentApplicationJsonSchema
    {
        /// <summary> Initializes a new instance of Paths2T1Oc0ResumeSearchEmbedPostRequestbodyContentApplicationJsonSchema. </summary>
        public Paths2T1Oc0ResumeSearchEmbedPostRequestbodyContentApplicationJsonSchema()
        {
        }

        /// <summary> Gets or sets the config override. </summary>
        public ResumeSearchConfig ConfigOverride { get; set; }
    }
}
