// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class Paths1BqdurzV2IndexGetResponses200ContentApplicationJsonSchemaAllof1
    {
        internal static Paths1BqdurzV2IndexGetResponses200ContentApplicationJsonSchemaAllof1 DeserializePaths1BqdurzV2IndexGetResponses200ContentApplicationJsonSchemaAllof1(JsonElement element)
        {
            Optional<IReadOnlyList<Index>> results = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("results"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<Index> array = new List<Index>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(Index.DeserializeIndex(item));
                    }
                    results = array;
                    continue;
                }
            }
            return new Paths1BqdurzV2IndexGetResponses200ContentApplicationJsonSchemaAllof1(Optional.ToList(results));
        }
    }
}
