// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Affinda.API.Models
{
    /// <summary> The Paths11QdcofV3MappingDataSourcesGetResponses200ContentApplicationJsonSchema. </summary>
    public partial class Paths11QdcofV3MappingDataSourcesGetResponses200ContentApplicationJsonSchema : PaginatedResponse
    {
        /// <summary> Initializes a new instance of Paths11QdcofV3MappingDataSourcesGetResponses200ContentApplicationJsonSchema. </summary>
        /// <param name="count"> Number of items in results. </param>
        internal Paths11QdcofV3MappingDataSourcesGetResponses200ContentApplicationJsonSchema(int count) : base(count)
        {
            Results = new ChangeTrackingList<MappingDataSource>();
        }

        /// <summary> Initializes a new instance of Paths11QdcofV3MappingDataSourcesGetResponses200ContentApplicationJsonSchema. </summary>
        /// <param name="count"> Number of items in results. </param>
        /// <param name="next"> URL to request next page of results. </param>
        /// <param name="previous"> URL to request previous page of results. </param>
        /// <param name="results"></param>
        internal Paths11QdcofV3MappingDataSourcesGetResponses200ContentApplicationJsonSchema(int count, string next, string previous, IReadOnlyList<MappingDataSource> results) : base(count, next, previous)
        {
            Results = results;
        }

        /// <summary> Gets the results. </summary>
        public IReadOnlyList<MappingDataSource> Results { get; }
    }
}
