// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class Paths1D5Zg6MV3AnnotationsGetResponses200ContentApplicationJsonSchema
    {
        internal static Paths1D5Zg6MV3AnnotationsGetResponses200ContentApplicationJsonSchema DeserializePaths1D5Zg6MV3AnnotationsGetResponses200ContentApplicationJsonSchema(JsonElement element)
        {
            Optional<IReadOnlyList<Annotation>> results = default;
            int count = default;
            Optional<string> next = default;
            Optional<string> previous = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("results"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<Annotation> array = new List<Annotation>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        if (item.ValueKind == JsonValueKind.Null)
                        {
                            array.Add(null);
                        }
                        else
                        {
                            array.Add(Annotation.DeserializeAnnotation(item));
                        }
                    }
                    results = array;
                    continue;
                }
                if (property.NameEquals("count"))
                {
                    count = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("next"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        next = null;
                        continue;
                    }
                    next = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("previous"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        previous = null;
                        continue;
                    }
                    previous = property.Value.GetString();
                    continue;
                }
            }
            return new Paths1D5Zg6MV3AnnotationsGetResponses200ContentApplicationJsonSchema(count, next.Value, previous.Value, Optional.ToList(results));
        }
    }
}
