// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class Paths1UtuacyResumeFormatsGetResponses200ContentApplicationJsonSchema
    {
        internal static Paths1UtuacyResumeFormatsGetResponses200ContentApplicationJsonSchema DeserializePaths1UtuacyResumeFormatsGetResponses200ContentApplicationJsonSchema(JsonElement element)
        {
            Optional<int> count = default;
            Optional<Uri> next = default;
            Optional<Uri> previous = default;
            Optional<IReadOnlyList<Get200ApplicationJsonPropertiesItemsItem>> results = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("count"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    count = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("next"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        next = null;
                        continue;
                    }
                    next = new Uri(property.Value.GetString());
                    continue;
                }
                if (property.NameEquals("previous"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        previous = null;
                        continue;
                    }
                    previous = new Uri(property.Value.GetString());
                    continue;
                }
                if (property.NameEquals("results"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<Get200ApplicationJsonPropertiesItemsItem> array = new List<Get200ApplicationJsonPropertiesItemsItem>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(Get200ApplicationJsonPropertiesItemsItem.DeserializeGet200ApplicationJsonPropertiesItemsItem(item));
                    }
                    results = array;
                    continue;
                }
            }
            return new Paths1UtuacyResumeFormatsGetResponses200ContentApplicationJsonSchema(Optional.ToNullable(count), next.Value, previous.Value, Optional.ToList(results));
        }
    }
}
