// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The ReformattedResumeData. </summary>
    public partial class ReformattedResumeData
    {
        /// <summary> Initializes a new instance of ReformattedResumeData. </summary>
        internal ReformattedResumeData()
        {
        }

        /// <summary> Initializes a new instance of ReformattedResumeData. </summary>
        /// <param name="reformattedFile"></param>
        internal ReformattedResumeData(string reformattedFile)
        {
            ReformattedFile = reformattedFile;
        }

        /// <summary> Gets the reformatted file. </summary>
        public string ReformattedFile { get; }
    }
}
