// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Affinda.API.Models
{
    /// <summary> The RequestError. </summary>
    public partial class RequestError
    {
        /// <summary> Initializes a new instance of RequestError. </summary>
        /// <param name="detail"></param>
        /// <param name="statusCode"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="detail"/> is null. </exception>
        internal RequestError(string detail, int statusCode)
        {
            if (detail == null)
            {
                throw new ArgumentNullException(nameof(detail));
            }

            Detail = detail;
            StatusCode = statusCode;
        }

        public string Detail { get; }
        public int StatusCode { get; }
    }
}
