// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Affinda.API.Models
{
    /// <summary> The ResumeSearchDetailOccupationGroup. </summary>
    public partial class ResumeSearchDetailOccupationGroup
    {
        /// <summary> Initializes a new instance of ResumeSearchDetailOccupationGroup. </summary>
        internal ResumeSearchDetailOccupationGroup()
        {
            Missing = new ChangeTrackingList<int>();
            Value = new ChangeTrackingList<ResumeSearchDetailOccupationGroupValueItem>();
        }

        /// <summary> Initializes a new instance of ResumeSearchDetailOccupationGroup. </summary>
        /// <param name="missing"></param>
        /// <param name="value"></param>
        internal ResumeSearchDetailOccupationGroup(IReadOnlyList<int> missing, IReadOnlyList<ResumeSearchDetailOccupationGroupValueItem> value)
        {
            Missing = missing;
            Value = value;
        }

        /// <summary> Gets the missing. </summary>
        public IReadOnlyList<int> Missing { get; }
        /// <summary> Gets the value. </summary>
        public IReadOnlyList<ResumeSearchDetailOccupationGroupValueItem> Value { get; }
    }
}
