// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class ResumeSearchScoreComponent
    {
        internal static ResumeSearchScoreComponent DeserializeResumeSearchScoreComponent(JsonElement element)
        {
            string label = default;
            Optional<string> value = default;
            Optional<float> score = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("label"))
                {
                    label = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("value"))
                {
                    value = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("score"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    score = property.Value.GetSingle();
                    continue;
                }
            }
            return new ResumeSearchScoreComponent(label, value.Value, Optional.ToNullable(score));
        }
    }
}
