// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Affinda.API.Models
{
    /// <summary> The ResumeDataEducationItemDates. </summary>
    public partial class ResumeDataEducationItemDates
    {
        /// <summary> Initializes a new instance of ResumeDataEducationItemDates. </summary>
        public ResumeDataEducationItemDates()
        {
        }

        /// <summary> Initializes a new instance of ResumeDataEducationItemDates. </summary>
        /// <param name="completionDate"></param>
        /// <param name="isCurrent"></param>
        /// <param name="startDate"></param>
        internal ResumeDataEducationItemDates(DateTimeOffset? completionDate, bool? isCurrent, DateTimeOffset? startDate)
        {
            CompletionDate = completionDate;
            IsCurrent = isCurrent;
            StartDate = startDate;
        }

        /// <summary> Gets or sets the completion date. </summary>
        public DateTimeOffset? CompletionDate { get; set; }
        /// <summary> Gets or sets the is current. </summary>
        public bool? IsCurrent { get; set; }
        /// <summary> Gets or sets the start date. </summary>
        public DateTimeOffset? StartDate { get; set; }
    }
}
