// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class ResumeSearchDetailEducationMissing
    {
        internal static ResumeSearchDetailEducationMissing DeserializeResumeSearchDetailEducationMissing(JsonElement element)
        {
            Optional<IReadOnlyList<string>> degrees = default;
            Optional<IReadOnlyList<string>> highestDegreeTypes = default;
            Optional<IReadOnlyList<string>> institutions = default;
            Optional<bool> currentStudent = default;
            Optional<bool> recentGraduate = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("degrees"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    degrees = array;
                    continue;
                }
                if (property.NameEquals("highestDegreeTypes"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    highestDegreeTypes = array;
                    continue;
                }
                if (property.NameEquals("institutions"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    institutions = array;
                    continue;
                }
                if (property.NameEquals("currentStudent"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    currentStudent = property.Value.GetBoolean();
                    continue;
                }
                if (property.NameEquals("recentGraduate"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    recentGraduate = property.Value.GetBoolean();
                    continue;
                }
            }
            return new ResumeSearchDetailEducationMissing(Optional.ToList(degrees), Optional.ToList(highestDegreeTypes), Optional.ToList(institutions), Optional.ToNullable(currentStudent), Optional.ToNullable(recentGraduate));
        }
    }
}
