// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class ResumeSearchDetailJobTitle
    {
        internal static ResumeSearchDetailJobTitle DeserializeResumeSearchDetailJobTitle(JsonElement element)
        {
            Optional<IReadOnlyList<string>> missing = default;
            Optional<IReadOnlyList<ResumeSearchDetailJobTitleValueItem>> value = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("missing"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    missing = array;
                    continue;
                }
                if (property.NameEquals("value"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<ResumeSearchDetailJobTitleValueItem> array = new List<ResumeSearchDetailJobTitleValueItem>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(ResumeSearchDetailJobTitleValueItem.DeserializeResumeSearchDetailJobTitleValueItem(item));
                    }
                    value = array;
                    continue;
                }
            }
            return new ResumeSearchDetailJobTitle(Optional.ToList(missing), Optional.ToList(value));
        }
    }
}
