// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class ResumeRedactData : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(RedactedPdf))
            {
                writer.WritePropertyName("redactedPdf");
                writer.WriteStringValue(RedactedPdf);
            }
            writer.WriteEndObject();
        }

        internal static ResumeRedactData DeserializeResumeRedactData(JsonElement element)
        {
            Optional<string> redactedPdf = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("redactedPdf"))
                {
                    redactedPdf = property.Value.GetString();
                    continue;
                }
            }
            return new ResumeRedactData(redactedPdf.Value);
        }
    }
}
