// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The ResumeDataRefereesItem. </summary>
    public partial class ResumeDataRefereesItem
    {
        /// <summary> Initializes a new instance of ResumeDataRefereesItem. </summary>
        internal ResumeDataRefereesItem()
        {
        }

        /// <summary> Initializes a new instance of ResumeDataRefereesItem. </summary>
        /// <param name="name"></param>
        /// <param name="text"></param>
        /// <param name="email"></param>
        /// <param name="number"></param>
        internal ResumeDataRefereesItem(string name, string text, string email, string number)
        {
            Name = name;
            Text = text;
            Email = email;
            Number = number;
        }

        /// <summary> Gets the name. </summary>
        public string Name { get; }
        /// <summary> Gets the text. </summary>
        public string Text { get; }
        /// <summary> Gets the email. </summary>
        public string Email { get; }
        /// <summary> Gets the number. </summary>
        public string Number { get; }
    }
}
