// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The ResumeDataWorkExperienceItem. </summary>
    public partial class ResumeDataWorkExperienceItem
    {
        /// <summary> Initializes a new instance of ResumeDataWorkExperienceItem. </summary>
        internal ResumeDataWorkExperienceItem()
        {
        }

        /// <summary> Initializes a new instance of ResumeDataWorkExperienceItem. </summary>
        /// <param name="id"></param>
        /// <param name="jobTitle"></param>
        /// <param name="socCode"></param>
        /// <param name="socName"></param>
        /// <param name="organization"></param>
        /// <param name="industry"></param>
        /// <param name="location"></param>
        /// <param name="jobDescription"></param>
        /// <param name="dates"></param>
        /// <param name="occupation"></param>
        internal ResumeDataWorkExperienceItem(int? id, string jobTitle, string socCode, string socName, string organization, string industry, Location location, string jobDescription, ResumeDataWorkExperienceItemDates dates, ResumeDataWorkExperienceItemOccupation occupation)
        {
            Id = id;
            JobTitle = jobTitle;
            SocCode = socCode;
            SocName = socName;
            Organization = organization;
            Industry = industry;
            Location = location;
            JobDescription = jobDescription;
            Dates = dates;
            Occupation = occupation;
        }

        /// <summary> Gets the id. </summary>
        public int? Id { get; }
        /// <summary> Gets the job title. </summary>
        public string JobTitle { get; }
        /// <summary> Gets the soc code. </summary>
        public string SocCode { get; }
        /// <summary> Gets the soc name. </summary>
        public string SocName { get; }
        /// <summary> Gets the organization. </summary>
        public string Organization { get; }
        /// <summary> Gets the industry. </summary>
        public string Industry { get; }
        /// <summary> Gets the location. </summary>
        public Location Location { get; }
        /// <summary> Gets the job description. </summary>
        public string JobDescription { get; }
        /// <summary> Gets the dates. </summary>
        public ResumeDataWorkExperienceItemDates Dates { get; }
        /// <summary> Gets the occupation. </summary>
        public ResumeDataWorkExperienceItemOccupation Occupation { get; }
    }
}
