// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The ResumeDataWorkExperienceItem. </summary>
    public partial class ResumeDataWorkExperienceItem
    {
        /// <summary> Initializes a new instance of ResumeDataWorkExperienceItem. </summary>
        internal ResumeDataWorkExperienceItem()
        {
        }

        /// <summary> Initializes a new instance of ResumeDataWorkExperienceItem. </summary>
        /// <param name="jobTitle"></param>
        /// <param name="organization"></param>
        /// <param name="location"></param>
        /// <param name="jobDescription"></param>
        /// <param name="dates"></param>
        /// <param name="occupation"></param>
        internal ResumeDataWorkExperienceItem(string jobTitle, string organization, Location location, string jobDescription, ResumeDataWorkExperienceItemDates dates, ResumeDataWorkExperienceItemOccupation occupation)
        {
            JobTitle = jobTitle;
            Organization = organization;
            Location = location;
            JobDescription = jobDescription;
            Dates = dates;
            Occupation = occupation;
        }

        /// <summary> Gets the job title. </summary>
        public string JobTitle { get; }
        /// <summary> Gets the organization. </summary>
        public string Organization { get; }
        /// <summary> Gets the location. </summary>
        public Location Location { get; }
        /// <summary> Gets the job description. </summary>
        public string JobDescription { get; }
        /// <summary> Gets the dates. </summary>
        public ResumeDataWorkExperienceItemDates Dates { get; }
        /// <summary> Gets the occupation. </summary>
        public ResumeDataWorkExperienceItemOccupation Occupation { get; }
    }
}
