// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class ResumeSearchMatchDetails
    {
        internal static ResumeSearchMatchDetails DeserializeResumeSearchMatchDetails(JsonElement element)
        {
            Optional<JobTitleSearchScoreComponent> jobTitle = default;
            Optional<ManagementLevelSearchScoreComponent> managementLevel = default;
            Optional<ExperienceSearchScoreComponent> experience = default;
            Optional<SkillsSearchScoreComponent> skills = default;
            Optional<LanguagesSearchScoreComponent> languages = default;
            Optional<LocationSearchScoreComponent> location = default;
            Optional<EducationSearchScoreComponent> education = default;
            Optional<OccupationGroupSearchScoreComponent> occupationGroup = default;
            Optional<SearchExpressionSearchScoreComponent> searchExpression = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("jobTitle"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    jobTitle = JobTitleSearchScoreComponent.DeserializeJobTitleSearchScoreComponent(property.Value);
                    continue;
                }
                if (property.NameEquals("managementLevel"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    managementLevel = ManagementLevelSearchScoreComponent.DeserializeManagementLevelSearchScoreComponent(property.Value);
                    continue;
                }
                if (property.NameEquals("experience"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    experience = ExperienceSearchScoreComponent.DeserializeExperienceSearchScoreComponent(property.Value);
                    continue;
                }
                if (property.NameEquals("skills"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    skills = SkillsSearchScoreComponent.DeserializeSkillsSearchScoreComponent(property.Value);
                    continue;
                }
                if (property.NameEquals("languages"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    languages = LanguagesSearchScoreComponent.DeserializeLanguagesSearchScoreComponent(property.Value);
                    continue;
                }
                if (property.NameEquals("location"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    location = LocationSearchScoreComponent.DeserializeLocationSearchScoreComponent(property.Value);
                    continue;
                }
                if (property.NameEquals("education"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    education = EducationSearchScoreComponent.DeserializeEducationSearchScoreComponent(property.Value);
                    continue;
                }
                if (property.NameEquals("occupationGroup"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    occupationGroup = OccupationGroupSearchScoreComponent.DeserializeOccupationGroupSearchScoreComponent(property.Value);
                    continue;
                }
                if (property.NameEquals("searchExpression"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    searchExpression = SearchExpressionSearchScoreComponent.DeserializeSearchExpressionSearchScoreComponent(property.Value);
                    continue;
                }
            }
            return new ResumeSearchMatchDetails(jobTitle.Value, managementLevel.Value, experience.Value, skills.Value, languages.Value, location.Value, education.Value, occupationGroup.Value, searchExpression.Value);
        }
    }
}
