// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The ResumeSearchParametersLocation. </summary>
    public partial class ResumeSearchParametersLocation
    {
        /// <summary> Initializes a new instance of ResumeSearchParametersLocation. </summary>
        public ResumeSearchParametersLocation()
        {
        }

        /// <summary> Initializes a new instance of ResumeSearchParametersLocation. </summary>
        /// <param name="name"></param>
        /// <param name="coordinates"></param>
        /// <param name="distance"></param>
        /// <param name="unit"></param>
        internal ResumeSearchParametersLocation(string name, ResumeSearchParametersLocationCoordinates coordinates, int? distance, SearchLocationUnit? unit)
        {
            Name = name;
            Coordinates = coordinates;
            Distance = distance;
            Unit = unit;
        }

        /// <summary> Gets or sets the name. </summary>
        public string Name { get; set; }
        /// <summary> Gets or sets the coordinates. </summary>
        public ResumeSearchParametersLocationCoordinates Coordinates { get; set; }
        /// <summary> Gets or sets the distance. </summary>
        public int? Distance { get; set; }
        /// <summary> Gets or sets the unit. </summary>
        public SearchLocationUnit? Unit { get; set; }
    }
}
