// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class ResumeDataWorkExperienceItemOccupation
    {
        internal static ResumeDataWorkExperienceItemOccupation DeserializeResumeDataWorkExperienceItemOccupation(JsonElement element)
        {
            Optional<string> jobTitle = default;
            Optional<string> jobTitleNormalized = default;
            Optional<string> emsiId = default;
            Optional<ManagementLevel?> managementLevel = default;
            Optional<Components1TryetgSchemasResumedataPropertiesWorkexperienceItemsPropertiesOccupationPropertiesClassification> classification = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("jobTitle"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        jobTitle = null;
                        continue;
                    }
                    jobTitle = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("jobTitleNormalized"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        jobTitleNormalized = null;
                        continue;
                    }
                    jobTitleNormalized = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("emsiId"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        emsiId = null;
                        continue;
                    }
                    emsiId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("managementLevel"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        managementLevel = null;
                        continue;
                    }
                    managementLevel = property.Value.GetString().ToManagementLevel();
                    continue;
                }
                if (property.NameEquals("classification"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        classification = null;
                        continue;
                    }
                    classification = Components1TryetgSchemasResumedataPropertiesWorkexperienceItemsPropertiesOccupationPropertiesClassification.DeserializeComponents1TryetgSchemasResumedataPropertiesWorkexperienceItemsPropertiesOccupationPropertiesClassification(property.Value);
                    continue;
                }
            }
            return new ResumeDataWorkExperienceItemOccupation(jobTitle.Value, jobTitleNormalized.Value, emsiId.Value, Optional.ToNullable(managementLevel), classification.Value);
        }
    }
}
