// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class ResumeDataSkillsItem : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Id))
            {
                writer.WritePropertyName("id");
                writer.WriteNumberValue(Id.Value);
            }
            if (Optional.IsDefined(Name))
            {
                writer.WritePropertyName("name");
                writer.WriteStringValue(Name);
            }
            if (Optional.IsDefined(LastUsed))
            {
                if (LastUsed != null)
                {
                    writer.WritePropertyName("lastUsed");
                    writer.WriteStringValue(LastUsed);
                }
                else
                {
                    writer.WriteNull("lastUsed");
                }
            }
            if (Optional.IsDefined(NumberOfMonths))
            {
                if (NumberOfMonths != null)
                {
                    writer.WritePropertyName("numberOfMonths");
                    writer.WriteNumberValue(NumberOfMonths.Value);
                }
                else
                {
                    writer.WriteNull("numberOfMonths");
                }
            }
            writer.WriteEndObject();
        }

        internal static ResumeDataSkillsItem DeserializeResumeDataSkillsItem(JsonElement element)
        {
            Optional<int> id = default;
            Optional<string> emsiId = default;
            Optional<string> name = default;
            Optional<string> lastUsed = default;
            Optional<int?> numberOfMonths = default;
            Optional<string> type = default;
            Optional<int?> count = default;
            Optional<float?> weighting = default;
            Optional<IReadOnlyList<ResumeDataSkillsPropertiesItemsItem>> sources = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("id"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    id = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("emsiId"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        emsiId = null;
                        continue;
                    }
                    emsiId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("lastUsed"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        lastUsed = null;
                        continue;
                    }
                    lastUsed = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("numberOfMonths"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        numberOfMonths = null;
                        continue;
                    }
                    numberOfMonths = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("count"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        count = null;
                        continue;
                    }
                    count = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("weighting"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        weighting = null;
                        continue;
                    }
                    weighting = property.Value.GetSingle();
                    continue;
                }
                if (property.NameEquals("sources"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<ResumeDataSkillsPropertiesItemsItem> array = new List<ResumeDataSkillsPropertiesItemsItem>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(ResumeDataSkillsPropertiesItemsItem.DeserializeResumeDataSkillsPropertiesItemsItem(item));
                    }
                    sources = array;
                    continue;
                }
            }
            return new ResumeDataSkillsItem(Optional.ToNullable(id), emsiId.Value, name.Value, lastUsed.Value, Optional.ToNullable(numberOfMonths), type.Value, Optional.ToNullable(count), Optional.ToNullable(weighting), Optional.ToList(sources));
        }
    }
}
