// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Affinda.API.Models
{
    /// <summary> The ResumeSearchDetailLocation. </summary>
    public partial class ResumeSearchDetailLocation
    {
        /// <summary> Initializes a new instance of ResumeSearchDetailLocation. </summary>
        internal ResumeSearchDetailLocation()
        {
            Missing = new ChangeTrackingList<ResumeSearchParametersLocation>();
        }

        /// <summary> Initializes a new instance of ResumeSearchDetailLocation. </summary>
        /// <param name="missing"></param>
        /// <param name="value"></param>
        internal ResumeSearchDetailLocation(IReadOnlyList<ResumeSearchParametersLocation> missing, ResumeSearchDetailLocationValue value)
        {
            Missing = missing;
            Value = value;
        }

        /// <summary> Gets the missing. </summary>
        public IReadOnlyList<ResumeSearchParametersLocation> Missing { get; }
        /// <summary> Gets the value. </summary>
        public ResumeSearchDetailLocationValue Value { get; }
    }
}
