// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The ResumeSearchDetailJobTitleValueItem. </summary>
    public partial class ResumeSearchDetailJobTitleValueItem
    {
        /// <summary> Initializes a new instance of ResumeSearchDetailJobTitleValueItem. </summary>
        internal ResumeSearchDetailJobTitleValueItem()
        {
        }

        /// <summary> Initializes a new instance of ResumeSearchDetailJobTitleValueItem. </summary>
        /// <param name="name"></param>
        /// <param name="startDate"></param>
        /// <param name="endDate"></param>
        /// <param name="companyName"></param>
        /// <param name="match"></param>
        internal ResumeSearchDetailJobTitleValueItem(string name, string startDate, string endDate, string companyName, bool? match)
        {
            Name = name;
            StartDate = startDate;
            EndDate = endDate;
            CompanyName = companyName;
            Match = match;
        }

        /// <summary> Gets the name. </summary>
        public string Name { get; }
        /// <summary> Gets the start date. </summary>
        public string StartDate { get; }
        /// <summary> Gets the end date. </summary>
        public string EndDate { get; }
        /// <summary> Gets the company name. </summary>
        public string CompanyName { get; }
        /// <summary> Gets the match. </summary>
        public bool? Match { get; }
    }
}
