// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class ResumeSearchDetailEducation
    {
        internal static ResumeSearchDetailEducation DeserializeResumeSearchDetailEducation(JsonElement element)
        {
            Optional<ResumeSearchDetailEducationMissing> missing = default;
            Optional<IReadOnlyList<ResumeSearchDetailEducationValueItem>> value = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("missing"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    missing = ResumeSearchDetailEducationMissing.DeserializeResumeSearchDetailEducationMissing(property.Value);
                    continue;
                }
                if (property.NameEquals("value"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<ResumeSearchDetailEducationValueItem> array = new List<ResumeSearchDetailEducationValueItem>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(ResumeSearchDetailEducationValueItem.DeserializeResumeSearchDetailEducationValueItem(item));
                    }
                    value = array;
                    continue;
                }
            }
            return new ResumeSearchDetailEducation(missing.Value, Optional.ToList(value));
        }
    }
}
