// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The ResumeSearchMatch. </summary>
    public partial class ResumeSearchMatch
    {
        /// <summary> Initializes a new instance of ResumeSearchMatch. </summary>
        internal ResumeSearchMatch()
        {
        }

        /// <summary> Initializes a new instance of ResumeSearchMatch. </summary>
        /// <param name="score"> The matching score between the provided resume and job description. </param>
        internal ResumeSearchMatch(float? score)
        {
            Score = score;
        }

        /// <summary> The matching score between the provided resume and job description. </summary>
        public float? Score { get; }
    }
}
