// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The RowAnnotation. </summary>
    public partial class RowAnnotation
    {
        /// <summary> Initializes a new instance of RowAnnotation. </summary>
        internal RowAnnotation()
        {
        }

        /// <summary> Initializes a new instance of RowAnnotation. </summary>
        /// <param name="code"></param>
        /// <param name="date"></param>
        /// <param name="description"></param>
        /// <param name="unit"></param>
        /// <param name="unitPrice"></param>
        /// <param name="quantity"></param>
        /// <param name="discount"></param>
        /// <param name="baseTotal"></param>
        /// <param name="taxRate"></param>
        /// <param name="taxTotal"></param>
        /// <param name="total"></param>
        /// <param name="other"></param>
        internal RowAnnotation(string code, string date, string description, string unit, float? unitPrice, float? quantity, string discount, float? baseTotal, string taxRate, float? taxTotal, float? total, string other)
        {
            Code = code;
            Date = date;
            Description = description;
            Unit = unit;
            UnitPrice = unitPrice;
            Quantity = quantity;
            Discount = discount;
            BaseTotal = baseTotal;
            TaxRate = taxRate;
            TaxTotal = taxTotal;
            Total = total;
            Other = other;
        }

        /// <summary> Gets the code. </summary>
        public string Code { get; }
        /// <summary> Gets the date. </summary>
        public string Date { get; }
        /// <summary> Gets the description. </summary>
        public string Description { get; }
        /// <summary> Gets the unit. </summary>
        public string Unit { get; }
        /// <summary> Gets the unit price. </summary>
        public float? UnitPrice { get; }
        /// <summary> Gets the quantity. </summary>
        public float? Quantity { get; }
        /// <summary> Gets the discount. </summary>
        public string Discount { get; }
        /// <summary> Gets the base total. </summary>
        public float? BaseTotal { get; }
        /// <summary> Gets the tax rate. </summary>
        public string TaxRate { get; }
        /// <summary> Gets the tax total. </summary>
        public float? TaxTotal { get; }
        /// <summary> Gets the total. </summary>
        public float? Total { get; }
        /// <summary> Gets the other. </summary>
        public string Other { get; }
    }
}
