// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Affinda.API.Models
{
    public partial class TableAnnotationParsed : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsCollectionDefined(Rows))
            {
                writer.WritePropertyName("rows");
                writer.WriteStartArray();
                foreach (var item in Rows)
                {
                    writer.WriteObjectValue(item);
                }
                writer.WriteEndArray();
            }
            writer.WriteEndObject();
        }

        internal static TableAnnotationParsed DeserializeTableAnnotationParsed(JsonElement element)
        {
            Optional<IList<RowAnnotation>> rows = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("rows"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<RowAnnotation> array = new List<RowAnnotation>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        if (item.ValueKind == JsonValueKind.Null)
                        {
                            array.Add(null);
                        }
                        else
                        {
                            array.Add(RowAnnotation.DeserializeRowAnnotation(item));
                        }
                    }
                    rows = array;
                    continue;
                }
            }
            return new TableAnnotationParsed(Optional.ToList(rows));
        }
    }
}
