// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Affinda.API.Models
{
    /// <summary> The TagCreate. </summary>
    public partial class TagCreate
    {
        /// <summary> Initializes a new instance of TagCreate. </summary>
        /// <param name="name"></param>
        /// <param name="workspace"> Uniquely identify a workspace. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="name"/> or <paramref name="workspace"/> is null. </exception>
        public TagCreate(string name, string workspace)
        {
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }
            if (workspace == null)
            {
                throw new ArgumentNullException(nameof(workspace));
            }

            Name = name;
            Workspace = workspace;
        }

        /// <summary> Gets the name. </summary>
        public string Name { get; }
        /// <summary> Uniquely identify a workspace. </summary>
        public string Workspace { get; }
    }
}
