// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The TagUpdate. </summary>
    public partial class TagUpdate
    {
        /// <summary> Initializes a new instance of TagUpdate. </summary>
        public TagUpdate()
        {
        }

        /// <summary> Gets or sets the name. </summary>
        public string Name { get; set; }
        /// <summary> Uniquely identify a workspace. </summary>
        public string Workspace { get; set; }
    }
}
