// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> The User. </summary>
    public partial class User
    {
        /// <summary> Initializes a new instance of User. </summary>
        internal User()
        {
        }

        /// <summary> Initializes a new instance of User. </summary>
        /// <param name="id"> Uniquely identify a user. </param>
        /// <param name="name"></param>
        /// <param name="username"></param>
        /// <param name="email"></param>
        /// <param name="avatar"> URL of the user&apos;s avatar. </param>
        internal User(string id, string name, string username, string email, string avatar)
        {
            Id = id;
            Name = name;
            Username = username;
            Email = email;
            Avatar = avatar;
        }

        /// <summary> Uniquely identify a user. </summary>
        public string Id { get; }
        /// <summary> Gets the name. </summary>
        public string Name { get; }
        /// <summary> Gets the username. </summary>
        public string Username { get; }
        /// <summary> Gets the email. </summary>
        public string Email { get; }
        /// <summary> URL of the user&apos;s avatar. </summary>
        public string Avatar { get; }
    }
}
