// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Affinda.API.Models
{
    /// <summary> Years of experience range. </summary>
    internal partial class YearsExperienceAnnotationUpdateParsed
    {
        /// <summary> Initializes a new instance of YearsExperienceAnnotationUpdateParsed. </summary>
        internal YearsExperienceAnnotationUpdateParsed()
        {
        }

        /// <summary> Initializes a new instance of YearsExperienceAnnotationUpdateParsed. </summary>
        /// <param name="minimum"> Minimum years of experience. </param>
        /// <param name="maximum"> Maximum years of experience. </param>
        internal YearsExperienceAnnotationUpdateParsed(float? minimum, float? maximum)
        {
            Minimum = minimum;
            Maximum = maximum;
        }

        /// <summary> Minimum years of experience. </summary>
        public float? Minimum { get; }
        /// <summary> Maximum years of experience. </summary>
        public float? Maximum { get; }
    }
}
