// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace affinda.Models
{
    /// <summary> The Get200ApplicationJsonPropertiesItemsItem. </summary>
    public partial class Get200ApplicationJsonPropertiesItemsItem
    {
        /// <summary> Initializes a new instance of Get200ApplicationJsonPropertiesItemsItem. </summary>
        /// <param name="identifier"></param>
        /// <param name="formatFile"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="identifier"/> or <paramref name="formatFile"/> is null. </exception>
        internal Get200ApplicationJsonPropertiesItemsItem(string identifier, Uri formatFile)
        {
            if (identifier == null)
            {
                throw new ArgumentNullException(nameof(identifier));
            }
            if (formatFile == null)
            {
                throw new ArgumentNullException(nameof(formatFile));
            }

            Identifier = identifier;
            FormatFile = formatFile;
        }

        public string Identifier { get; }
        public Uri FormatFile { get; }
    }
}
