// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace affinda.Models
{
    public partial class Paths1VouiekRedactedResumesPostResponses201ContentApplicationJsonSchema
    {
        internal static Paths1VouiekRedactedResumesPostResponses201ContentApplicationJsonSchema DeserializePaths1VouiekRedactedResumesPostResponses201ContentApplicationJsonSchema(JsonElement element)
        {
            Optional<string> fileName = default;
            Optional<string> identifier = default;
            Optional<bool> redactHeadshot = default;
            Optional<bool> redactPersonalDetails = default;
            Optional<bool> redactWorkDetails = default;
            Optional<bool> redactEducationDetails = default;
            Optional<bool> redactReferees = default;
            Optional<bool> redactLocations = default;
            Optional<bool> redactDates = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("fileName"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        fileName = null;
                        continue;
                    }
                    fileName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("identifier"))
                {
                    identifier = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("redactHeadshot"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    redactHeadshot = property.Value.GetBoolean();
                    continue;
                }
                if (property.NameEquals("redactPersonalDetails"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    redactPersonalDetails = property.Value.GetBoolean();
                    continue;
                }
                if (property.NameEquals("redactWorkDetails"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    redactWorkDetails = property.Value.GetBoolean();
                    continue;
                }
                if (property.NameEquals("redactEducationDetails"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    redactEducationDetails = property.Value.GetBoolean();
                    continue;
                }
                if (property.NameEquals("redactReferees"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    redactReferees = property.Value.GetBoolean();
                    continue;
                }
                if (property.NameEquals("redactLocations"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    redactLocations = property.Value.GetBoolean();
                    continue;
                }
                if (property.NameEquals("redactDates"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    redactDates = property.Value.GetBoolean();
                    continue;
                }
            }
            return new Paths1VouiekRedactedResumesPostResponses201ContentApplicationJsonSchema(fileName.Value, identifier.Value, Optional.ToNullable(redactHeadshot), Optional.ToNullable(redactPersonalDetails), Optional.ToNullable(redactWorkDetails), Optional.ToNullable(redactEducationDetails), Optional.ToNullable(redactReferees), Optional.ToNullable(redactLocations), Optional.ToNullable(redactDates));
        }
    }
}
