// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace affinda.Models
{
    /// <summary> The RedactedDocument. </summary>
    public partial class RedactedDocument
    {
        /// <summary> Initializes a new instance of RedactedDocument. </summary>
        internal RedactedDocument()
        {
        }

        /// <summary> Initializes a new instance of RedactedDocument. </summary>
        /// <param name="data"></param>
        /// <param name="meta"></param>
        /// <param name="error"></param>
        internal RedactedDocument(RedactedDocumentData data, Meta meta, Error error)
        {
            Data = data;
            Meta = meta;
            Error = error;
        }

        public RedactedDocumentData Data { get; }
        public Meta Meta { get; }
        public Error Error { get; }
    }
}
